### ISSUE TITLE
SVpop gets stuck on certain chromosomes

### ISSUE THREAD

**Issue by pietermonsieurs** [mattravenhall/SV-Pop#4]
When running SVpop on a set of 16 vcf files (created using Delly), SVpop hangs on certain chromosomes. This seems quite reproducible, as always the same chromosome gave issues. This is confirmed when filtering the vcf files for each chromosome separately, and running  SVpop on a per-chromosomes basis. When running SVpop on a super computer, the issue starts when suddenly the memory incraease (using up to 100G of RAM), followed by the full usage of the 2Gb swap space. This seems rather strange to me, as the input file only consist of a few Mb of data.

So we can get output files for some chromosomes (*_v1_windows_annotated_v1.1.csv), and even concatenate them using simple bash commands, run PREPROCESS and do visualization. However, as said, for some chromosomes the output "_v1_windows_annotated_v1.1.csv" is not created.

**Comment by mattravenhall** [comment]
Hey, thanks for raising this issue. I've not seen behaviour like this before so will need to investigate properly. Would you be able to send me an example of one of the chromosome files that is causing this issue?

**Comment by pietermonsieurs** [comment]
Hi Matt,

Thanks for the reply. I have added the log files (logfile.tar.gz), the input vcf-files (.zip), the SampleFiles.txt and the gff file of the genome.

The command I am using is: 
/user/antwerpen/205/vsc20587/scratch/plasmodium_svpop/software/SV-Pop/Analysis/SVPop \
-F=SampleFiles.txt \
-M=DUP \
-R=PlasmoDB-46_PvivaxP01.gff \
--refFormat=gff \
--multithreads=True \
--threads=20 \
--suppressWarnings=False

[SampleFiles.txt](https://github.com/mattravenhall/SV-Pop/files/4911519/SampleFiles.txt)
[delly_vcfs.zip](https://github.com/mattravenhall/SV-Pop/files/4911501/delly_vcfs.zip)
[log_files.tar.gz](https://github.com/mattravenhall/SV-Pop/files/4911514/log_files.tar.gz)
[PlasmoDB-46_PvivaxP01.gff.zip](https://github.com/mattravenhall/SV-Pop/files/4911625/PlasmoDB-46_PvivaxP01.gff.zip)

**Comment by mattravenhall** [comment]
Hey Pieter,

I think the issue here is that you're specifying too many threads for your input files. By specifying 20 threads, you'll be loading in 20 chromosomes at once (as well as the gff file and various internal variables). That issue will be worse when you're loading in larger chromosomes with more variants. The vcf files you provided range from 2 to 14 Gb in size.

The memory issue is likely being compounded by your vcf files containing multiple SV types. Pre-version 1.2, your input vcf files must consist of one sample and one SV type. You can find a support script for splitting a single sample vcf file into DEL, DUP, INS, and INV subset [in the wiki](https://github.com/mattravenhall/SV-Pop/wiki/Setup-Support-Scripts).

I've added a SV type filter in the latest commit (commit [a352886](https://github.com/mattravenhall/SV-Pop/commit/a35288632ece1a35f599e43d9fc76499fccc813c), version 1.2). With that filter applied, the analysis stage for the provided files successfully completed in under five minutes when using 2 threads on my desktop PC (16Gb RAM). If you're using version 1.2 you will not need to split your vcf files into SV type specific files.

I would suggest updating to version 1.2 and running with fewer threads (try 10, then try fewer if you hit your memory limit). Also ensure that other users are not hogging RAM on the system at the same time.

**Comment by pietermonsieurs** [comment]
Thanks for the advice. Installing version 1.2 indeed solved the issue, even when keeping the number of threads to 20. (for you information: the input vcf files where varying between 2 and 14 Mb, not Gb). 
Thanks for the support!

**Comment by mattravenhall** [comment]
No worries, I've updated my previous comment to correct the Gb/Mb typo and will close this bug.
